# Generated by Django 2.1 on 2020-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip_done',
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6, null=True, verbose_name='邮编'),
        ),
    ]
